<?php 
	$data=array(
		'SP01'=>array(
			'name'=>'cat',
			'price'=>'1000000',
			'quantity'=>5,
			'img'=>'cat.PNG',
		),
		'SP02'=>array(
			'name'=>'dog',
			'price'=>'2000000',
			'quantity'=>5,
			'img'=>'dog.png',
		),
		'SP03'=>array(
			'name'=>'hamster',
			'price'=>'3000000',
			'quantity'=>5,
			'img'=>'hamster.PNG',
		),
		'SP04'=>array(
			'name'=>'Thor',
			'price'=>'4000000',
			'quantity'=>5,
			'img'=>'Thor.PNG',
		),
		'SP05'=>array(
			'name'=>'Caption',
			'price'=>'5000000',
			'quantity'=>5,
			'img'=>'Caption.PNG',
		),
		'SP06'=>array(
			'name'=>'Malefident',
			'price'=>'6000000',
			'quantity'=>5,
			'img'=>'Malefident.PNG',
		),
		'SP07'=>array(
			'name'=>'Hulk',
			'price'=>'7000000',
			'quantity'=>5,
			'img'=>'Hulk.PNG',
		),
	);

 ?>